INSERT INTO `Author` VALUES (1001, ' 宋興洲', '政治經濟學、國際政治、社會科學計量研究法', '東海大學');
INSERT INTO `Author` VALUES (1002, ' 王(糸秀)線', '日本語文學', '輔仁大學');
INSERT INTO `Author` VALUES (1003, ' 吳柏林', '時間數列分析與預測、應用統計和模糊理論', '臺灣國立政治大學');
INSERT INTO `Author` VALUES (1004, ' 喬健', '人類學系', '美國康乃爾大學');
INSERT INTO `Author` VALUES (1005, ' 王力堅', '中國文學系專任教授兼系主任', '臺灣國立中央大學');
INSERT INTO `Author` VALUES (1006, ' 李亦園', '無', '蔣經國國際學術交流基金會董事長');
INSERT INTO `Author` VALUES (1007, ' 高少凡', '中國與東協研究、東亞與東南亞區域研究、國際關係理論與實務', '東海大學');
INSERT INTO `Author` VALUES (1008, ' 梁碧峰', '化學', '東海大學');
INSERT INTO `Author` VALUES (1009, ' 趙庭輝', '無', '英國伯明罕大學');
INSERT INTO `Author` VALUES (1010, ' 戴麗珠', '國文研究所博士', '臺灣師範大學');
INSERT INTO `Author` VALUES (1011, ' 陳運財', '無', '東海的法律學院代理院長');
INSERT INTO `Author` VALUES (1012, ' 謝世忠', '族群理論、西南中國民族誌、大陸東南亞民族誌、泰學研究、寮學研究、詮釋人類學、民族史方法論、觀光人類學、第四世界論述、臺灣原住民文化、發展人類學', '美國西雅圖華盛頓大學');
INSERT INTO `Author` VALUES (1013, ' 陳世興', '無', '南華大學');
INSERT INTO `Author` VALUES (1014, ' 賀德芬', '憲法、智慧財產權、傳播法規、教育法規、性別與法律', '國立台灣大學');
INSERT INTO `Author` VALUES (1015, '  陳建仁', '地方自治、民主理論、東亞研究、電子化治理', '東海大學');
INSERT INTO `Author` VALUES (1016, ' 石路', '無', '法國里昂第三大學');
INSERT INTO `Author` VALUES (1017, ' 黃樹民', '臺灣漢人社會、中國華南社會、泰北社會文化研究', '愛荷華州立大學');
INSERT INTO `Author` VALUES (1018, ' 張慧銖', '資訊組織、主題分析、圖書館管理、生物醫學資源', '輔仁大學');
INSERT INTO `Author` VALUES (1019, ' 唐淑美', '生物科技法、醫療法、專利法、科技與管理', '英國雪菲爾大學');
INSERT INTO `Author` VALUES (1020, ' 陳平坤', '無', '中山大學');
INSERT INTO `Author` VALUES (1021, ' 楊祖漢', '無', '無');
INSERT INTO `Author` VALUES (1022, ' 魏世萍', '日本文化', '東吳大學');
INSERT INTO `Author` VALUES (1023, ' 王建生', '中國文學', '東海大學');
INSERT INTO `Author` VALUES (1024, ' 江明修', '非營利組織、研究方法論、行政改革∕行政倫理、組織理論∕行政理論、人力資源管理與發展', '美國南加州大學');
INSERT INTO `Author` VALUES (1025, ' 呂珍玉', '無', '東海大學');
INSERT INTO `Author` VALUES (1027, ' 黃文倩', '中國現當代文學、文學批評與理論', '淡江大學');
INSERT INTO `Author` VALUES (1028, ' 蔡岳勳', '無', '國防大學管理學院');
INSERT INTO `Author` VALUES (1029, ' 曹雄源', '國際政治、比較政治、國際安全、中共軍事研究、國防經濟學、美國國家安全戰略研究、美國國防政策研究專案管理', '英國伯明罕大學');
INSERT INTO `Author` VALUES (1030, ' 林熊徵', '自動化控制、控制系統、機電整合、電力電子、網路監控', '臺灣師範大學');
INSERT INTO `Author` VALUES (1032, ' 林尚義', '無', '國立台灣藝術大學');
INSERT INTO `Author` VALUES (1033, '  約瑟琺．拉羅許', '社會科學、國際關係', '法國巴黎第一大學');
INSERT INTO `Author` VALUES (1034, ' 臺大鏡社', '無', '無');
INSERT INTO `Author` VALUES (1035, ' 馬漢寶', '國際法', '國立臺灣大學');
INSERT INTO `Author` VALUES (1036, ' 賴文英', '無', '輔仁大學');
INSERT INTO `Author` VALUES (1037, ' 丁守中', '法律', 'The Fletcher School');
INSERT INTO `Author` VALUES (1038, ' 劉坤靈', '無', '中華民國創業投資公會產業顧問');
INSERT INTO `Author` VALUES (1040, ' 新台灣人文教基金會', '無', '無');
INSERT INTO `Author` VALUES (1042, ' 徐聖凱', '社會科學、教育、教育史/教育研究', '國立臺灣師範大學');
INSERT INTO `Author` VALUES (1044, ' 祝均宙', '中國史地', '無');
INSERT INTO `Author` VALUES (1045, ' 林慶彰', '台灣史地', '東吳大學');
INSERT INTO `Author` VALUES (1046, ' 曾文培', '社會科學', '無');
INSERT INTO `Author` VALUES (1048, ' 潘朝陽', '中國哲學', '無');
INSERT INTO `Author` VALUES (1050, ' 史勇偉', '中醫養生', '皇朝飯店');
INSERT INTO `Author` VALUES (1051, ' 盧詩韻', '藝術理論', '國立臺中教育大學');
INSERT INTO `Author` VALUES (1053, ' 朱我芯', '華語學習', '國立臺灣師範大學');
INSERT INTO `Author` VALUES (1054, ' 熊秉元', '法律', '無');
INSERT INTO `Author` VALUES (1056, ' 劉家和', '人文史地', '無');
INSERT INTO `Author` VALUES (1057, ' 李紀祥', '人文史地', '佛光大學');
INSERT INTO `Author` VALUES (1058, ' 文藻外語學院', '外語學習', '文藻外語學院');
INSERT INTO `Author` VALUES (1060, ' 蔡丁耀', '華文創作', '高苑科技大學');
INSERT INTO `Author` VALUES(1062,'王次澄','中華民國國家文學博士','臺灣國立中央大學');
INSERT INTO `Author` VALUES(1063,'簡明哲','以公益為目的之非營利、非政府組織','財團法人新台灣人文教基金會');
INSERT INTO `Author` VALUES(1066,'郭永吉','中國文學系助理教授','國立中央大學');
INSERT INTO `Author` VALUES(1067,'黃文吉','中文研究所碩士、博士','東吳大學');
INSERT INTO `Author` VALUES(1068,'林陳涌','科學教育研究所教授暨師資培育處與就業輔導處處長','國立臺灣師範大學');
INSERT INTO `Author` VALUES(1069,'林建光','台灣文學所','國立中興大學');
INSERT INTO `Author` VALUES(1071,'邱韻芳','人類學研究所','國立暨南大學');
INSERT INTO `Author` VALUES(1072,'顧力仁','臺灣大學圖書資訊學博士','臺北大學');
INSERT INTO `Author` VALUES(1074,'楊崇森','智慧財產法、民商法、英美法、信託法、仲裁法、司法制度','國立臺北大學');
INSERT INTO `Author` VALUES(1075,'人力資源管理學報編委會','國內人力資源領域  最具代表性的學術刊物','人力資源管理學報編委會');
INSERT INTO `Author` VALUES(1076,'楊秋忠','無','無');
INSERT INTO `Author` VALUES(1077,'岑丞丕','無','無');
INSERT INTO `Author` VALUES(1078,'張富祥','歷史系教授、齊魯文化研究中心研究員、博士','山東大學');
INSERT INTO `Author` VALUES(1079,'須文蔚','以公益為目的之非營利、非政府組織','無');
INSERT INTO `Author` VALUES(1080,'蔡榮祥','政治學系專任教授','國立中正大學');
INSERT INTO `Author` VALUES(1081,'中華民國科學教育學會','無','中華民國科學教育學會');
INSERT INTO `Author` VALUES(1083,'潘英海','無','無');
INSERT INTO `Author` VALUES(1084,'懷爾德','翻譯、作詞家、演員、大學教授及編劇者','無');
INSERT INTO `Author` VALUES(1087,'王向華','流行文化、東亞創意產業及企業研究','香港大學');
INSERT INTO `Author` VALUES(1089,'謝榮峰','華人工藝行銷、節慶活動公關、公設交響樂團、博物館、國際藝術節及數個公部門的文化行政等','中山大學');
INSERT INTO `Author` VALUES(1090,'邱振中','書法理論、詩歌與藝術創作','中央美術學院');
INSERT INTO `Author` VALUES(1092,'胡心蘭','法學院法律系專任助理教授','東海大學');
INSERT INTO `Author` VALUES(1095,'約瑟琺‧拉羅許','政治系教授','「經濟與社會」研究室');
INSERT INTO `Author` VALUES(1096,'王文純','無','無');
INSERT INTO `Author` VALUES (1101, '吳豐維', '康德哲學、倫理學與法政哲學', '文化大學');
INSERT INTO `Author` VALUES (1102, '郭澤寬', '小說、音樂劇場、現代戲劇、台灣文化研究等', '國立東華大學');
INSERT INTO `Author` VALUES (1103, '衛民', '公共事務管理學', '臺北大學');
INSERT INTO `Author` VALUES (1105, '王宏文', '公共財務管理、政策分析、公共管理、與食品安全管理等', '國立臺灣大學政治學系暨政治學');
INSERT INTO `Author` VALUES (1107, '謝明憲', '經學、先秦兩漢魏晉南北朝學術史、敘事學', '國立清華大學');
INSERT INTO `Author` VALUES (1108, '黃元鶴', '知識與創新管理、圖書館管理、專利檢索與分析、資訊計量與學術傳播等', '輔仁大學');
INSERT INTO `Author` VALUES (1109, '李怡賡', '劇場／舞台設計', '海籽劇團');
INSERT INTO `Author` VALUES (1110, '顏瓊芬', '生態人文學', '靜宜大學');
INSERT INTO `Author` VALUES (1111, '王梅玲', '圖書資訊與檔案學', '國立政治大學');
INSERT INTO `Author` VALUES (1113, '張文朝', '中日經學比較', '中央研究院');
INSERT INTO `Author` VALUES (1115, '劉佩玲', '土木工程', '國立中興大學');
INSERT INTO `Author` VALUES (1116, '陳清秀', '法律學', '東吳大學');
INSERT INTO `Author` VALUES (1117, '林美聆', '無', '無');
INSERT INTO `Author` VALUES (1118, '董醒任', '無', 'Taipei Tzu Chi Hospital, Buddhist Tzu Chi Medical Foundation');
INSERT INTO `Author` VALUES (1119, '林殷齊', '藝術概論、視覺藝術與多元文化、性別與藝術等', '國立高雄師範大學');
INSERT INTO `Author` VALUES (1120, '田阡', '族群與區域文化、非物質文化遺產、流域人類學', '西南大學');
INSERT INTO `Author` VALUES (1121, '楊國樞', '心理學', '中央研究院');
INSERT INTO `Author` VALUES (1123, '古清華', '法律學', '信業法律事務所');
INSERT INTO `Author` VALUES (1125, '陳靖博', '臨床毒物學、血液透析、腹膜透析、副甲狀腺機能亢進之研究', '長庚大學醫學院');
INSERT INTO `Author` VALUES (1128, '熊存瑞', 'history', 'Western Michigan University');
