INSERT INTO `Chapters` VALUES (200101, '從三都十五縣政策論地方民意代表性的問題', '宋興洲、李文堂');
INSERT INTO `Chapters` VALUES (200102, '我國覆議制度之研究─中央與地方的比較', '呂炳寬、張峻豪');
INSERT INTO `Chapters` VALUES (200103, '三都十五縣與區域治理', '黃建銘');
INSERT INTO `Chapters` VALUES (200104, '都會治理能力之分析：以台中都會區大眾運輸問題為例', '李長晏、賴志奎');
INSERT INTO `Chapters` VALUES (200105, '都市治理與社會空間階層化－高雄市都市空間發展之討論', '李俊豪');
INSERT INTO `Chapters` VALUES (200106, '地方政府透明化之分析與評估－以桃園縣龜山鄉為例', '陳朝建');
INSERT INTO `Chapters` VALUES (200107, '臺灣國土空間規劃一點多心與地方發展策略設計評析', '紀俊臣、蔡承叡');
INSERT INTO `Chapters` VALUES (200108, '政治市場之議題價值與企業非市場策略意涵', '蕭元哲');
INSERT INTO `Chapters` VALUES (200109, '科學園區開發案之政策網絡分析－以中科三期后里基地開發案為例', '魯俊孟、羅奕麟');
INSERT INTO `Chapters` VALUES (200110, '觀光產業行銷策略規劃：新竹縣個案分析', '黃國敏、張碧琴');
INSERT INTO `Chapters` VALUES (200111, '台中縣市合併升格對地方政治生態影響初探', '黃信達');
INSERT INTO `Chapters` VALUES (200112, '施政表現與選民投票抉擇：以2005年縣市長選舉為例', '許勝懋');
INSERT INTO `Chapters` VALUES (200113, '推動「地方特色產業」的政策比較－以日本、泰國及台灣為例', '廖舜右、許峻賓');
INSERT INTO `Chapters` VALUES (200114, '「新」中央與地方關係媒介的研究－以歐洲議會與其黨團分析', '王啟明');
INSERT INTO `Chapters` VALUES (200115, '從第一波民主化國家發展審視地方自治對民主穩定之影響', '陳建仁、謝秉憲');
INSERT INTO `Chapters` VALUES (200116, '全球化浪潮下國際移民對移入社會之影響－比較德國與台灣當前移工╱移民政策與其影響', '余健慈');
INSERT INTO `Chapters` VALUES (200201, '芥川龍之介兒童文學之研究', ' 王(糸秀)線');
INSERT INTO `Chapters` VALUES (200301, '現代教育與心理統計學', '吳柏林、謝名娟');
INSERT INTO `Chapters` VALUES (200401, '拿瓦侯傳統之延續(增修訂版)', '喬健');
INSERT INTO `Chapters` VALUES (200501, '魏晉詩歌的審美觀照(修訂版)', '王力堅');
INSERT INTO `Chapters` VALUES (200601, '文化與修養', '李亦園');
INSERT INTO `Chapters` VALUES (200701, '海洋論壇會議實錄', '高少凡、陳建仁');
INSERT INTO `Chapters` VALUES (200801, '無機化學實驗', '梁碧峰');
INSERT INTO `Chapters` VALUES (200901, '敘事電影與性別論述', '趙庭輝');
INSERT INTO `Chapters` VALUES (201001, '文學與美學的交會：戴麗珠教授論文集', '戴麗珠');
INSERT INTO `Chapters` VALUES (201101, '刑事司法與國際人權公約學術研討會實錄', '陳運財');
INSERT INTO `Chapters` VALUES (201201, '餵雞屋人類學：迷妳論述101', '謝世忠');
INSERT INTO `Chapters` VALUES (201301, '輕鬆搞定！用Google雲端技術架設電子商務網站&手機APP開發', '陳世興');
INSERT INTO `Chapters` VALUES (201401, '疾風勁草：著作權的風雨歲月', '賀德芬');
INSERT INTO `Chapters` VALUES (201501, '從中央支配到地方自主：日本地方分權改革的軌跡與省思', '陳建仁');
INSERT INTO `Chapters` VALUES (201601, '中國城市用語', '石路、劉海岩');
INSERT INTO `Chapters` VALUES (201701, '林村的故事：一九四九年後的中國農村變革（增訂版）', '黃樹民');
INSERT INTO `Chapters` VALUES (201801, '圖書館電子資源組織：從書架到網路', '張慧銖');
INSERT INTO `Chapters` VALUES (201901, '從風險預測談犯罪相關理論應用驗證──以預防被害與自我保護為題', ' 施茂林 ');
INSERT INTO `Chapters` VALUES (201902, '刑事妥速審判法草案之立法風險控管', '蔡佩芬 ');
INSERT INTO `Chapters` VALUES (201903, '從臺灣高等法院高雄分院刑事九五年度上更（二）字第一六九號判決談校園法律責任', '蘇滿麗');
INSERT INTO `Chapters` VALUES (201904, '不動產交易與風險管理之探討', '吳容明');
INSERT INTO `Chapters` VALUES (201905, '企業法律責任及法律控管之研究', '方國輝 ');
INSERT INTO `Chapters` VALUES (201906, '跨國投資與法律風險管理──以臺商在大陸投資盈餘匯出的租稅規劃為例', '謝如蘭');
INSERT INTO `Chapters` VALUES (201907, '美國2008年金融危機之成因與影響──以金融市場中之風險為重心', '楊君毅');
INSERT INTO `Chapters` VALUES (201908, '政府作為與法律風險管理──以國家賠償為中心', '張智聖');
INSERT INTO `Chapters` VALUES (201909, '風力發電的法律風險管理', '陳匡正');
INSERT INTO `Chapters` VALUES (201910, '論新興生物科技之法律風險──從「臺灣生物資料庫」建置之窘境談起', '唐淑美 ');
INSERT INTO `Chapters` VALUES (202001, '惠我良多──感恩楊惠南老師', '劉嘉誠');
INSERT INTO `Chapters` VALUES (202002, '飛越在理性與感性之上──向楊惠南教授致敬', '陳嘉璟');
INSERT INTO `Chapters` VALUES (202003, '楊柳春風，詩文皇皇──為詩皇楊風賀壽', '林建德');
INSERT INTO `Chapters` VALUES (202004, '往事煙雲──我所認識的楊惠南老師', '陳平坤');
INSERT INTO `Chapters` VALUES (202005, '論《阿含經》中「無常即苦」之命題', '洪嘉琳');
INSERT INTO `Chapters` VALUES (202006, '龍樹與休姆對有神論的批判之比較研究', '劉嘉誠');
INSERT INTO `Chapters` VALUES (202007, '從《中論》的對反詞組析探其思維理路', '林建德');
INSERT INTO `Chapters` VALUES (202008, '「迦羅」（Kala）或「三摩耶」（Samaya）？──以「時間」議題論《大智度論》批判實在論的哲學問題', '嚴瑋泓');
INSERT INTO `Chapters` VALUES (202009, '邏輯或解經學──初期大乘瑜伽行派「四種道理」理論性格之探究', '林鎮國');
INSERT INTO `Chapters` VALUES (202010, '在解脫學脈絡下的佛身論──以《攝大乘論》為中心之探討', '耿　晴');
INSERT INTO `Chapters` VALUES (202011, '僧肇〈不真空論〉的實相哲學', '陳平坤');
INSERT INTO `Chapters` VALUES (202012, '《壇經》研究方法的反省與拓展──從《壇經》的版本考證談起', '何照清');
INSERT INTO `Chapters` VALUES (202013, '從《瑜伽論記》析論〈真實義品〉「離言自性」的語言哲學及對「說一切有部」語言觀的批判', '趙東明');
INSERT INTO `Chapters` VALUES (202014, '華嚴宗形上學命題的知識意義', '杜保瑞');
INSERT INTO `Chapters` VALUES (202015, '儒理與禪法的合流──以大慧宗杲思想為中心的考察', '林義正');
INSERT INTO `Chapters` VALUES (202016, '自然與自性──論北宋自然禪偈中的時空感知及其作用', '陳嘉璟');
INSERT INTO `Chapters` VALUES (202017, '巴壺天對「禪公案」的詮釋', '邱敏捷');
INSERT INTO `Chapters` VALUES (202018, '佛教走向土地倫理──「人間淨土」的省思', '林朝成');
INSERT INTO `Chapters` VALUES (202019, '佛教禪修做為心身安頓──以基礎觀念與關鍵概念為線索', '蔡耀明');
INSERT INTO `Chapters` VALUES (202101, '黃宗羲與明末清初學術', '楊祖漢、楊自平');
INSERT INTO `Chapters` VALUES (202201, '日本文化教科書研究論文集', '魏世萍');
INSERT INTO `Chapters` VALUES (202301, '山水詩研究論稿', '王建生');
INSERT INTO `Chapters` VALUES (202401, '社會企業與公益創新：邁向公民社會', '江明修');
INSERT INTO `Chapters` VALUES (202501, '《詩經》末章變調詩篇研究', '呂珍玉');
INSERT INTO `Chapters` VALUES (202502, '《詩經》之敘述視點及視點、聚焦模糊詩篇詩旨問題探討 ', '呂珍玉');
INSERT INTO `Chapters` VALUES (202503, '《詩經》頂真修辭技巧探究 ', '呂珍玉');
INSERT INTO `Chapters` VALUES (202504, '《詩經》中的名言探究', '呂珍玉');
INSERT INTO `Chapters` VALUES (202505, '概念譬喻理論的詩歌詮釋------以《詩經．摽有梅》為例', '林增文');
INSERT INTO `Chapters` VALUES (202506, '分化中的統一------《詩經．巧言》的總體性隱喻閱讀', '林增文');
INSERT INTO `Chapters` VALUES (202507, '《詩經》中的情感表現探討', '賴曉臻');
INSERT INTO `Chapters` VALUES (202508, '《詩經》抒情方法探討 ', '賴曉臻');
INSERT INTO `Chapters` VALUES (202509, '《詩經》男性人物形象塑造技巧', '譚莊蘭');
INSERT INTO `Chapters` VALUES (202510, '《詩經》諷刺藝術研究', '林芹竹');
INSERT INTO `Chapters` VALUES (202511, '《管錐編．毛詩正義》論《詩》之修辭、句法與表達藝術', '張惠婷');
INSERT INTO `Chapters` VALUES (202601, '著作權法論文集：著作權的基礎磐石','賀德芬');
INSERT INTO `Chapters` VALUES (202701, '在巨流中擺渡：「探求者」的文學道路與創作困境', '黃文倩');
INSERT INTO `Chapters` VALUES (202801, '當代國際新能源政策與法制發展','蔡岳勳');
INSERT INTO `Chapters` VALUES (202901, '美國國安會簡史','曹雄源');
INSERT INTO `Chapters` VALUES (203001, '機器人介面與控制設計實務','林熊徵');
INSERT INTO `Chapters` VALUES (203101, '著作權法論文集：著作權的實務個案','賀德芬');
INSERT INTO `Chapters` VALUES (203201, '劇場藝術的多元發展與設計：從劇場形式解析舞台設計','林尚義');
INSERT INTO `Chapters` VALUES (203301, '跨國主義分析全球局勢：法國觀點2009-2010','約瑟琺．拉羅許');
INSERT INTO `Chapters` VALUES (203401, '透視臺大：鏡社實錄','臺大鏡社');
INSERT INTO `Chapters` VALUES (203501, '法律與中國社會之變遷(增訂本)','馬漢寶');
INSERT INTO `Chapters` VALUES (203601, '語言變體與區域方言：以臺灣新屋客語為例','賴文英');
INSERT INTO `Chapters` VALUES (203701, 'The Dilemma of Disintegration: Nationalist China’s Policy Toward Japan, 1931-1937','丁守中 Ting Shou-chung');
INSERT INTO `Chapters` VALUES (203801, '創業Let’s Go！風險投資之中國紀行','劉坤靈');
INSERT INTO `Chapters` VALUES (203901, '中國詩人詞人曲家賞析','戴麗珠');
INSERT INTO `Chapters` VALUES (204001, '南北差異：區域失衡之結與解析','辛翠玲');
INSERT INTO `Chapters` VALUES (204002, '產業政策：產業政策之總體環境與永續成長','葉國俊');
INSERT INTO `Chapters` VALUES (204003, '政黨政治：選制變革對政黨政治之影響','陳敏鳳');
INSERT INTO `Chapters` VALUES (204004, '國會運作：當前國會運作之省思','鄭任汶');
INSERT INTO `Chapters` VALUES (204005, '政媒關係：政策溝通與媒體互動之檢視','賴祥蔚');
INSERT INTO `Chapters` VALUES (204006, '智庫發展：日本經驗對我國智庫發展之啟示','邵軒磊');
INSERT INTO `Chapters` VALUES (204101, '跨國主義分析全球局勢：法國觀點2011', ' 約瑟琺．拉羅許 ');
INSERT INTO `Chapters` VALUES (204201, '日治時期臺北高等學校與菁英養成', ' 徐聖凱');
INSERT INTO `Chapters` VALUES (204301, '化學與人生', ' 梁碧峰 ');
INSERT INTO `Chapters` VALUES (204401, '圖鑑百年文獻：晚清民國年間畫報源流特點探究', ' 祝均宙 ');
INSERT INTO `Chapters` VALUES (204501, '屈萬里先生與圖書辨偽', ' 林慶彰 ');
INSERT INTO `Chapters` VALUES (204502, '劉兆祐先生與圖書辨偽', ' 林慶彰 ');
INSERT INTO `Chapters` VALUES (204503, '當代文學禁書研究', ' 林慶彰 ');
INSERT INTO `Chapters` VALUES (204504, '臺灣商務印書館竄改《東方雜誌》重印本', ' 林慶彰 ');
INSERT INTO `Chapters` VALUES (204505, '戒嚴時期《國魂》月刊所刊登的禁書', ' 林慶彰 ');
INSERT INTO `Chapters` VALUES (204506, '呂思勉先生著作在臺灣的翻印及流傳', ' 林慶彰 ');
INSERT INTO `Chapters` VALUES (204507, '高亨先生著作在臺灣的翻印及流傳', ' 林慶彰 ');
INSERT INTO `Chapters` VALUES (204508, '張舜徽先生著作在臺灣的翻印及流傳', ' 林慶彰 ');
INSERT INTO `Chapters` VALUES (204509, '誰剽竊朱自清的著作', ' 林慶彰 ');
INSERT INTO `Chapters` VALUES (204510, '九本詩學入門書', ' 林慶彰 ');
INSERT INTO `Chapters` VALUES (204511, '趙景深《中國文學小史》在臺灣的翻印本 ', ' 林慶彰 ');
INSERT INTO `Chapters` VALUES (204601, '數位正義E世代', ' 曾文培 ');
INSERT INTO `Chapters` VALUES (204701, '圖鑑百年文獻：晚清民國年間期刊源流特點探究', ' 祝均宙 ');
INSERT INTO `Chapters` VALUES (204801, '儒家的禮與祭祀篇', ' 潘朝陽 ');
INSERT INTO `Chapters` VALUES (204802, '儒學與跨文化哲學篇', ' 潘朝陽 ');
INSERT INTO `Chapters` VALUES (204901, '當代新儒家與儒家倫常篇', ' 潘朝陽 ');
INSERT INTO `Chapters` VALUES (204902, '東亞儒家倫常篇', ' 潘朝陽 ');
INSERT INTO `Chapters` VALUES (205001, ' 養生之道', ' 史勇偉 ');
INSERT INTO `Chapters` VALUES (205101, 'New Media as Performance in Site-specific Art', ' 盧詩韻  ');
INSERT INTO `Chapters` VALUES (205201, '圖鑑百年文獻：晚清民國年間小報源流特點探究', ' 祝均宙 ');
INSERT INTO `Chapters` VALUES (205301, '對外華語文化教學實證研究：以跨文化溝通與第二文化習得為導向', ' 朱我芯 ');
INSERT INTO `Chapters` VALUES (205401, '法學的經濟思惟', ' 熊秉元 ');
INSERT INTO `Chapters` VALUES (205501, '跨國主義分析全球局勢：法國觀點2012', ' 約瑟琺．拉羅許 ');
INSERT INTO `Chapters` VALUES (205601, '史學與思想', ' 劉家和 ');
INSERT INTO `Chapters` VALUES (205701, '時間.歷史.敘事', ' 李紀祥 ');
INSERT INTO `Chapters` VALUES (205801, '越南語（一）(附CD)', ' 文藻外語學院 ');
INSERT INTO `Chapters` VALUES (205901, '國際私法學說之發展與派別', ' 馬漢寶 ');
INSERT INTO `Chapters` VALUES (205902, '涉外案件之處理及國際私法之立法在中國之發展', ' 馬漢寶 ');
INSERT INTO `Chapters` VALUES (205903, '談國際私法案件之處理', ' 馬漢寶 ');
INSERT INTO `Chapters` VALUES (205904, '國際私法規則之特性及相關問題', ' 馬漢寶 ');
INSERT INTO `Chapters` VALUES (205905, '國際私法上之專門名詞及其用法', ' 馬漢寶 ');
INSERT INTO `Chapters` VALUES (206001, '散文小集', ' 蔡丁耀 ');
INSERT INTO `Chapters` VALUES (206002, '童言童語你我他', ' 蔡丁耀 ');
INSERT INTO `Chapters` VALUES (206003, '童話', ' 蔡丁耀 ');
INSERT INTO `Chapters` VALUES (206004, '親子樂融融', ' 蔡丁耀 ');
INSERT INTO `Chapters` VALUES (206005, '農事甘苦談', ' 蔡丁耀 ');
INSERT INTO `Chapters` VALUES (206006, '節能減碳救地球', ' 蔡丁耀 ');
INSERT INTO `Chapters` VALUES (206101,'回眸青春：中國知青文學（增訂版）','王力堅');
INSERT INTO `Chapters` VALUES (206201,'引言','王次澄');
INSERT INTO `Chapters` VALUES (206202,'兩漢六朝學風轉變中的博學現象','郭永吉');
INSERT INTO `Chapters` VALUES (206203,'謝靈運〈述祖德詩〉發微 —— 兼及晉宋之際陳郡陽夏謝氏子弟的境遇','陳慶元');
INSERT INTO `Chapters` VALUES (206204,'象闕與蕭梁政權始建期的正統焦慮 —— 讀陸倕〈石闕銘〉','程章燦');
INSERT INTO `Chapters` VALUES (206205,'吾今一死初無憾，願把孤忠托孟堅：華岳詩作研析','盧慶濱');
INSERT INTO `Chapters` VALUES (206206,'宋末元初的文學語言 —— 晚唐體的走向','內山');
INSERT INTO `Chapters` VALUES (206207,'辨析汪元量之「遺民」身分及其集句詞所流露之另類心聲','王偉勇');
INSERT INTO `Chapters` VALUES (206208,'陳普〈詠史〉組詩文、史、哲之會通合體 —— 以詠評三國、兩晉人物為例','王次澄');
INSERT INTO `Chapters` VALUES (206209,'Alter World: The “Dreamland” of Dong Yue and Late Ming Buddhism','Lynn A. Struve');
INSERT INTO `Chapters` VALUES (206210,'清初遺民文秉之史著與史學','吳振漢');
INSERT INTO `Chapters` VALUES (206211,'關於彭劍南的戲曲《影梅庵》與《香畹樓》','大木');
INSERT INTO `Chapters` VALUES (206212,'論晚清民初人情派小說的變異 —— 從「海上」系列小說到《歇浦潮》','呂文翠');
INSERT INTO `Chapters` VALUES (206213,'馬克思主義與中國知識份子 —— 以陳獨秀及毛澤東為例','齊茂吉');
INSERT INTO `Chapters` VALUES (206301,'文化論述政策與執行','吳昆財');
INSERT INTO `Chapters` VALUES (206302,'就醫之路好遠，好辛苦','廖學志');
INSERT INTO `Chapters` VALUES (206401,'清領時期臺灣儒學參考文獻','林慶彰');
INSERT INTO `Chapters` VALUES (206501,'讀書‧札記','戴麗珠');
INSERT INTO `Chapters` VALUES (206601,'六朝家庭經學教育與博學風氣研究','郭永吉');
INSERT INTO `Chapters` VALUES (206701,'黃文吉古典文學論集','黃文吉');
INSERT INTO `Chapters` VALUES (206801,'緒論','王如哲');
INSERT INTO `Chapters` VALUES (206802,'中國大陸科學教育師資培育制度','劉秀曦');
INSERT INTO `Chapters` VALUES (206803,'香港科學教育師資培育制度','蘇進棻');
INSERT INTO `Chapters` VALUES (206804,'韓國科學教育師資培育制度','黃月純');
INSERT INTO `Chapters` VALUES (206805,'日本科學師資培育制度','楊武勳');
INSERT INTO `Chapters` VALUES (206806,'新加坡科學師資培育制度','許民忠');
INSERT INTO `Chapters` VALUES (206807,'臺灣科學教育師資培育制度','劉欣宜');
INSERT INTO `Chapters` VALUES (206901,'賽伯格與後人類主義',' 林建光');
INSERT INTO `Chapters` VALUES (207001,'評松本雅明著《關於《詩經》諸篇成立的研究》','白川靜');
INSERT INTO `Chapters` VALUES (207002,'評《關於《詩經》諸篇成立的研究》','蘭契奧蒂');
INSERT INTO `Chapters` VALUES (207003,'評松本雅明氏《關於《詩經》諸篇成立的研究》','吉川幸次郎');
INSERT INTO `Chapters` VALUES (207004,'評松本雅明著《關於《詩經》諸篇成立的研究》','山田統');
INSERT INTO `Chapters` VALUES (207005,'評松本雅明著《關於《詩經》諸篇成立的研究','友枝龍太郎');
INSERT INTO `Chapters` VALUES (207006,'徂徠學中的《詩經》','若水俊');
INSERT INTO `Chapters` VALUES (207007,'葛蘭言（Marcel Grant）的《詩經》研究：《中國古代的祭禮與歌謠》','鄭誼慧');
INSERT INTO `Chapters` VALUES (207008,'戴震和日本古學派','約翰‧艾倫‧塔克');
INSERT INTO `Chapters` VALUES (207009,'楊慎的詩論','橫田輝俊');
INSERT INTO `Chapters` VALUES (207010,'宣爐因緣──方拱乾與冒襄','大木康');
INSERT INTO `Chapters` VALUES (207011,'俞樾與日本、韓國人士交往考略','陳東輝');
INSERT INTO `Chapters` VALUES (207012,'中國古典文學蘇俄流播史論','陳友冰');
INSERT INTO `Chapters` VALUES (207013,'我的履歷','諸橋轍');
INSERT INTO `Chapters` VALUES (207014,'炳麟西來—夏含夷教授探研中國古代文化史的歷程與成就','馮曉庭');
INSERT INTO `Chapters` VALUES (207101,'祖靈與上帝：花蓮太魯閣人的宗教變遷與復振運動','邱韻芳');
INSERT INTO `Chapters` VALUES (207201,'編者序','林慶彰');
INSERT INTO `Chapters` VALUES (207202,'《新、舊五代史》載錄經學史料述略','馮曉庭');
INSERT INTO `Chapters` VALUES (207301,'讀汪紹楹〈阮氏重刻宋本十三經注疏考〉','李霖');
INSERT INTO `Chapters` VALUES (207302,'淺議呂柟及《周易說翼》教育思想','邢春華');
INSERT INTO `Chapters` VALUES (207303,'論陳喬樅、皮錫瑞《尚書》學之異同','劉德州');
INSERT INTO `Chapters` VALUES (207304,'抗戰時期的《詩序》研究','林慶彰');
INSERT INTO `Chapters` VALUES (207305,'顧頡剛先生《周禮》研究淺識','張濤');
INSERT INTO `Chapters` VALUES (207306,'洪誠先生禮學管窺','顧遷');
INSERT INTO `Chapters` VALUES (207307,'芻論李源澄之學術觀','李弘毅');
INSERT INTO `Chapters` VALUES (207308,'安井小太郎研究文獻目錄','陳亦伶');
INSERT INTO `Chapters` VALUES (207309,'朱子經學及其在東亞的流傳與發展國際學術研討會','編輯部');
INSERT INTO `Chapters` VALUES (207310,'新中國六十年的經學研究（1950-2010）第三次國際學術研討會','編輯部');
INSERT INTO `Chapters` VALUES (207311,'新中國六十年的經學研究（1950-2010）第四次國際學術研討會','編輯部');
INSERT INTO `Chapters` VALUES (207312,'安井小太郎研究文獻目錄','陳亦伶');
INSERT INTO `Chapters` VALUES (207401,'遨遊美國法：美國法之源流與民刑法之運作','岑丞丕');
INSERT INTO `Chapters` VALUES (207501,'台灣人力資源管理與組織行為研究回顧','人力資源管理學報編委會');
INSERT INTO `Chapters` VALUES (207601,'Soil and Fertilizer: Concepts and Practice','楊秋忠');
INSERT INTO `Chapters` VALUES (207701,'林語堂生平小傳','楊崇森');
INSERT INTO `Chapters` VALUES (207801,'《竹書紀年》與夏商周年代研究','張富祥');